### ISSUE TITLE
generate_outputs can no longer generate an 'image'

### ISSUE THREAD

**Issue by IsabelLipartito** [MazinLab/MKIDPipeline#46]
I think a recent change to getFits caused this error because I was able to generate 'images' before.  

Traceback (most recent call last):
  File "/scratch/isabel/mec/HD984/runpipeline_HD984.py", line 80, in <module>
    generate_outputs(outputs)
  File "/scratch/isabel/mec/HD984/runpipeline_HD984.py", line 62, in generate_outputs
2019-07-23 18:01:43,113 DEBUG sample_times: [1545458415] (pid=12201)
    applyTPFWeight=o.enable_noise, countRate=True)
  File "/home/isabel/src/mkidpipeline/mkidpipeline/hdf/photontable.py", line 833, in getFits
2019-07-23 18:01:43,120 DEBUG Correction angles: [0.17336044] (pid=12201)
    header.update(wcs.to_header())
AttributeError: 'Header' object has no attribute 'to_header'

Process finished with exit code 1

**Comment by baileyji** [comment]
This looks like a side effect of 48d740a from @RupertDodkins. @RupertDodkins since you changed the specification of get_wcs() youll need to go through the entire codebase and find all usages of them and make sure the change is compatible, looks like at a minimum getFits needs to be fixed as it no longer needs to call to_header().
