### ISSUE TITLE
Temporal Drizzler has issue in forming hypercube

### ISSUE THREAD

**Issue by IsabelLipartito** [MazinLab/MKIDPipeline#47]
It starts to make the hypercube:

```
Number of WCS axes: 2
CTYPE : 'RA--TAN'  'DEC-TAN'  
CRVAL : 34.355884579167  28.744649518056  
CRPIX : 176.0  176.0  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : 2.8888888888889e-06  2.8888888888889e-06  
NAXIS : 0  0 (pid=27411)
2019-08-01 11:55:00,708 WARNING Increasing the number of time bins beyond the user request (pid=27411)
```
And then we have a failure:

```
Traceback (most recent call last):
  File "/mnt/data0/isabel/mec/HD10680/HD10680_12222018/runpipeline_HD10680_12222018.py", line 80, in <module>
    generate_outputs(outputs)
  File "/mnt/data0/isabel/mec/HD10680/HD10680_12222018/runpipeline_HD10680_12222018.py", line 69, in generate_outputs
    pixfrac=config.drizzler.pixfrac, usecache=False, intt=60, derotate=True, exp_timestep=60)
  File "/home/isabel/src/mkidpipeline/mkidpipeline/imaging/drizzler.py", line 801, in form
    driz.run()
  File "/home/isabel/src/mkidpipeline/mkidpipeline/imaging/drizzler.py", line 437, in run
    counts = self.makeTess(dither_photons, (self.wcs_times_ms[t], self.wcs_times_ms[t+1]))
  File "/home/isabel/src/mkidpipeline/mkidpipeline/imaging/drizzler.py", line 489, in makeTess
    hypercube, _ = np.histogramdd(sample.T, bins, weights=weights)
  File "/home/isabel/.conda/envs/astroworld/lib/python3.6/site-packages/numpy/lib/function_base.py", line 987, in histogramdd
    mindiff = dedges[i].min()
  File "/home/isabel/.conda/envs/astroworld/lib/python3.6/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

Process finished with exit code 1
```

**Comment by baileyji** [comment]
Looking at that stack trace it reads like the histogram is failing because it tries to take the minimum of an empty array. Might try checking to see if the sample, bins, and weights being passed to histogramdd are properly populated (e.g. was the data loaded in and do they have common-sense values and dimensions).

**Comment by IsabelLipartito** [comment]
This was my bad, I was specifying too long an exposure time.  It runs to completion
