### ISSUE TITLE
drizzler.compare_images has an issue

### ISSUE THREAD

**Issue by IsabelLipartito** [MazinLab/MKIDPipeline#48]
```
    quickplot = True
    if quickplot:
        drizzle.compare_images()
        # drizzle.quick_pretty_plot()
```
If we try to call compare_images():

```
Traceback (most recent call last):
 File "/mnt/data0/isabel/mec/LkCa15/runpipeline_LkCa15.py", line 78, in <module>
   generate_outputs(outputs)
 File "/mnt/data0/isabel/mec/LkCa15/runpipeline_LkCa15.py", line 68, in generate_outputs
   pixfrac=config.drizzler.pixfrac, usecache=False, derotate=True, exp_timestep=75, wcs_timestep=75)
 File "/home/isabel/src/mkidpipeline/mkidpipeline/imaging/drizzler.py", line 806, in form
   drizzle.compare_images()
 File "/home/isabel/src/mkidpipeline/mkidpipeline/imaging/drizzler.py", line 677, in compare_images
   self.expmap[0,0],
TypeError: 'NoneType' object is not subscriptable
```

This only appears if quickplot=True

**Comment by RupertDodkins** [comment]
I guess the issue still persists even if it doesn't show up with the default behaviour. I will more rigorously address this once the other more pressing issues are resolved
