### ISSUE TITLE
name 'PHOTON_SIZE_BYTES' is not defined (in bin2hdf)

### ISSUE THREAD

**Issue by IsabelLipartito** [MazinLab/MKIDPipeline#55]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/envs/pipeline/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/opt/anaconda3/envs/pipeline/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/isabel/src/mkidpipeline/mkidpipeline/hdf/bin2hdf.py", line 461, in runbuilder
    b.run()
  File "/home/isabel/src/mkidpipeline/mkidpipeline/hdf/bin2hdf.py", line 450, in run
    build_pytables(self.cfg, **self.kwargs)
  File "/home/isabel/src/mkidpipeline/mkidpipeline/hdf/bin2hdf.py", line 68, in build_pytables
    ram_est_gb = estimate_ram_gb(cfg.datadir, cfg.starttime, cfg.inttime) + 2  #add some headroom
  File "/home/isabel/src/mkidpipeline/mkidpipeline/hdf/bin2hdf.py", line 58, in estimate_ram_gb
    return n_max_photons*PHOTON_SIZE_BYTES/1024/1024/1024
NameError: name 'PHOTON_SIZE_BYTES' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runpipeline.py", line 45, in <module>
    run_stage1(dataset)
  File "runpipeline.py", line 31, in run_stage1
    pipe.bin2hdf.buildtables(dataset.timeranges, ncpu=ncpu, remake=False, chunkshape=250)
  File "/home/isabel/src/mkidpipeline/mkidpipeline/hdf/bin2hdf.py", line 499, in buildtables
    pool.map(runbuilder, builders)
  File "/opt/anaconda3/envs/pipeline/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/anaconda3/envs/pipeline/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
NameError: name 'PHOTON_SIZE_BYTES' is not defined

**Comment by steigersg** [comment]
should have been "PHOTON_BIN_SIZE_BYTES", was fixed
