### ISSUE TITLE
name mismatch in data.yaml and out.yaml passes validation

### ISSUE THREAD

**Issue by KristinaDavis** [MazinLab/MKIDPipeline#65]
======MEMORY PID=3630688====== <Synchronized wrapper for c_double(0.0)>
2021-09-07 17:43:28 mkidcore.objects            :DEBUG    (_load:210[pid=3630688]) Reading /darkdata/MEC/20210902/20210815_final.bmap
2021-09-07 17:43:28 mkidpipeline.config         :DEBUG    (__init__:309[pid=3630688]) Storing duration as _duration for use by subclass
2021-09-07 17:43:28 mkidpipeline.config         :DEBUG    (__init__:309[pid=3630688]) Storing duration as _duration for use by subclass
2021-09-07 17:43:28 mkidpipeline.config         :DEBUG    (__init__:309[pid=3630688]) Storing duration as _duration for use by subclass
2021-09-07 17:43:28 mkidpipeline.config         :DEBUG    (__init__:309[pid=3630688]) Storing duration as _duration for use by subclass
2021-09-07 17:43:28 mkidpipeline.config         :DEBUG    (__init__:309[pid=3630688]) Storing duration as _duration for use by subclass
2021-09-07 17:43:28 mkidpipeline.config         :DEBUG    (_find_nested:1163[pid=3630688]) Skipping nested search of unassociated "wavecal0" for wavecal
2021-09-07 17:43:28 mkidpipeline.config         :ERROR    (__init__:1490[pid=3630688]) Unable to find data description for "CDI 20210902 White Light i"
2021-09-07 17:43:28 mkidpipeline.config         :ERROR    (__init__:1490[pid=3630688]) Unable to find data description for "CDI 20210902 White Light ii"
2021-09-07 17:43:28 mkidpipeline.config         :ERROR    (__init__:1490[pid=3630688]) Unable to find data description for "CDI 20210902 White Light iii"
2021-09-07 17:43:28 mkidpipeline.config         :ERROR    (__init__:1490[pid=3630688]) Unable to find data description for "CDI 20210902 White Light iv"
2021-09-07 17:43:28 mkidpipeline.config         :ERROR    (__init__:1490[pid=3630688]) Unable to find data description for "CDI 20210902 White Light v"
2021-09-07 17:43:28 mkidpipeline.config         :ERROR    (__init__:1490[pid=3630688]) Unable to find data description for "CDI 20210902 White Light vi"
2021-09-07 17:43:28 mkidpipeline.config         :WARNING  (__iter__:1142[pid=3630688]) Iterating on a dataset excludes nested definitions
Traceback (most recent call last):
  File "/home/kkdavis/.conda/envs/pipeline/bin/mkidpipe", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/work/kkdavis/src/MKIDPipeline/scripts/mkidpipe", line 111, in <module>
    issue_report = outputs.validation_summary(null_success=True)
  File "/work/kkdavis/src/MKIDPipeline/mkidpipeline/config.py", line 1504, in validation_summary
    errors = self.validate(return_errors=True)
  File "/work/kkdavis/src/MKIDPipeline/mkidpipeline/config.py", line 1539, in validate
    e = [f'{o.wavecal} missing for {o.name} ' for o in set(self.to_wavecal) if isinstance(o.wavecal, str)]
  File "/work/kkdavis/src/MKIDPipeline/mkidpipeline/config.py", line 1651, in to_wavecal
    for o in out.data.obs:
AttributeError: 'str' object has no attribute 'obs'

**Comment by baileyji** [comment]
Would you either attach your yaml or point me to their path?
