### ISSUE TITLE
Unable to make drizzled output with timestep less than duration - start_offset

### ISSUE THREAD

**Issue by nswimmer** [MazinLab/MKIDPipeline#81]
Trying to test the effect of changing wcs_timestep (in pipe.yaml) and timestep (in out.yaml) has resulted in behavior where the temporal drizzle cannot successfully be made. The relevant blocks/yaml configurations can be seen at the end of the block.

What I have found is that when creating a temporal drizzle, if I decrease the `timestep` in the `!MKIDOutput` block below the value set by `duration-start_offset` (set in `!MKIDDither` and `!MKIDOutput`, respectively), the `mkidpipe --make-outputs` command fails with the error
```
Traceback (most recent call last):
  File "/home/nswimmer/.conda/envs/pipeline/bin/mkidpipe", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/nswimmer/src/mkidpipeline/scripts/mkidpipe", line 113, in <module>
    steps.output.generate(outputs)
  File "/home/nswimmer/src/mkidpipeline/mkidpipeline/steps/output.py", line 77, in generate
    **kwargs)
  File "/home/nswimmer/src/mkidpipeline/mkidpipeline/steps/drizzler.py", line 732, in form
    driz.run(apply_weight=weight)
  File "/home/nswimmer/src/mkidpipeline/mkidpipeline/steps/drizzler.py", line 397, in run
    self.wcs = self.generate_wcs(wave=nwvls != 1, time=nexp_time != 1)
  File "/home/nswimmer/src/mkidpipeline/mkidpipeline/steps/drizzler.py", line 441, in generate_wcs
    w.wcs.crpix = [self.wcs.wcs.crpix[0], self.wcs.wcs.crpix[1]]
ValueError: 'crpix' array is the wrong shape, must be 3
```
although `mkidpipe --vet` succeeds with no warnings/issues. Rerunning this same code with `timestep=15` results in a successful run to completion and creation of a temporal output cube. This is also independent of `adi_mode` being true or false, the same error appears in both cases.

**Side Note:** The `duration` keyword is not initialized anywhere in the YAML files after running `mkidpipe --init`, but the script will error out if not specified. Should this be generated somewhere by the init command? 

Data Block is
```
- !MKIDDither
  name: hip99770_dither_0 # A name
  data: 1634445412.0 # A list of !sob composing the dither, a unix time that falls within the range of a dither log in paths.data, or a fully qualified legacy (starttimes, endtimes, xpos,ypos) dither file.
  wavecal: wavecal0 # A MKIDWavedata or name of the same
  flatcal: flatcal0 # A MKIDFlatdata or name of the same
  wcscal: wcscal0 # A MKIDWCSCal or name of the same
  speccal: '' # A MKIDSpecdata or name of the same
  duration: 20
  use: 0,1,2,3,4,5,6,7,8 # Specify which dither obs to use, list or range specification string e.g. #,#-#,#,#
  header: # A dictionary of fits header key overrides, to be applied to the observations
    OBJECT: Hip 99770 # Object
```

Output Block is
```
- !MKIDOutput
  name: hip99770_dither_0_case3-1_tpsf8_twcs20_tbin1_adi  # A name
  data: hip99770_dither_0 # An data name
  kind: drizzle # drizzle - Use drizzlerimage - Generate a simple image (use photontable.get_fits)movie - Use movies to generate a gif animationtcube - use photontable.get_fitsscube - use photontable.get_fits
  exclude_flags: # A list of pixel flag names to exclude
  min_wave: 950.0 nm # Wavelength start for wavelength sensitive outputs
  max_wave: 1375.0 nm # Wavelength stop for wavelength sensitive outputs,
  start_offset: 5.0 # start offset (s) into data (per frame if dithered)
  units: photons # photons|photons/s. Drizzled data will always be in photons/s
  use_weights: true # Use photon weights
  adi_mode: true # Output compatible with ADI pipeline - do not apply any rotation to outputs (If True will overwrite derotate)
  lincal: false # Apply and use lincal, slow
  pixcal: true # Apply pixcal
  cosmical: false # Determine cosmic ray hits, slow
  flatcal: true # Apply flatcal
  movie_runtime: 0.0 # Runtime of movie, defaults to realtime
  timestep: 1.0 # Duration of time bins in output cubes with a temporal axis (None means no temporal axis)
  wavestep: 0.0 nm # Width of wavelength bins in output cubes with a wavelength axis
```

pipe.yaml is
```
!pipe_cfg
instrument: !InstrumentInfo
  deadtime_us: 10
  energy_bin_width_ev: 0.1
  minimum_wavelength: 700
  filter_cutoff_min: 950
  maximum_wavelength: 1500
  nominal_platescale_mas: 10.4
  device_orientation_deg: -48.26
  maximum_count_rate: 5000
  name: MEC
ncpu: 10  # number of cpus
verbosity: 0 # level of verbosity
flow: # Calibration steps to apply and order in which to do them
- buildhdf
- attachmeta
- wavecal
#- pixcal
#- flatcal
#- cosmiccal
#- speccal
paths: !configdict
  data: /darkdata/ScienceData/Subaru/  # bin file parent folder, must contain YYYYMMDD/*.bin and YYYYMMDD/logs/
  database: /work/nswimmer/20211016/database # calibrations will be retrieved/stored here
  out: /work/nswimmer/20211016/injectp/rrate0/ # root of output
#  out: /work/nswimmer/20211016/injectp/rrate1/ # root of output
  tmp: /work/nswimmer/scratch # use for data intensive temp files
beammap: !bmap  # A Beammap to use
  file: /darkdata/MEC/20211016/20210815_final.bmap
  freqfiles: /darkdata/MEC/20211016/data/metadata_20210812*_clipped.txt
  nrows: 146
  ncols: 140
buildhdf: !buildhdf_cfg
  remake: false  # Remake H5 even if they exist
  include_baseline: false # Include the baseline in H5 phase/wavelength column
  chunkshape: 250 # HDF5 Chunkshape to use
cosmiccal: !cosmiccal_cfg
  plots: all  # Which plots to generate
  wavecut: # An optional range (min_nm, max_nm) to use for CR detection
  method: threshold # What method to use to identify CR impacts (threshold|poisson)
  removal_range: # The number of microseconds before and after an event to filter
  - 50
  - 100
drizzler: !drizzler_cfg
  plots: all  # Which plots to generate: none|summary|all
  pixfrac: 0.5 # The drizzle algorithm pixel fraction
  wcs_timestep: 15.0 # Seconds between different WCS (eg orientations). If None, the the non-blurring minimum (1 pixel at furthest dither center) will be used
  whitelight: false # If True will not expect an OBJECT, RA, or DEC in the header and will only use the CONEX position to calculate the WCS. Used for bench tests where data is not taken
  save_steps: false # Save intermediate fits files where possible (only some modes)
  usecache: false # Cache photontable for subsequent runs
  ncpu: 1 # Number of CPUs to use
  clearcache: false # Clear user cache on next run
flatcal: !flatcal_cfg
  rate_cutoff: 0  # Count Rate Cutoff in inverse seconds (number)
  trim_chunks: 1 # number of Chunks to trim (integer)
  chunk_time: 10 # duration of chunks used for weights (s)
  nchunks: 6 # number of chunks to median combine
  power: 1 # power of polynomial to fit, <3 advised
  use_wavecal: true # Use a wavelength dependant correction for wavecaled data.
  plots: summary # none|summary|all
lincal: !lincal_cfg
  dt: 1000  # time range over which to calculate the weights (us)
movies: !movies_cfg
  type: simple  # simple|upramp|both
  colormap: viridis # Colormap to use
  rate_cut: # Count (rate) cutoff, None=none
  axes: true # Show the axes
  wcs: true # Use the WCS solution
  dpi: # Image writer DPI
  mask_bad: true # Mask bad pixels
  fps: 24 # framerate
  smoothing: !configdict
    n:  # Smooth over N frames
    sigma: # >n-sigma outliers will be smoothed
    power: # Power for Savitgy-Golay filter
  inpaint_below: 0  # Counts below limit will be inpainted (0=off)
  stretch: !configdict
    name: linear  # linear | asinh | log | power[power=5] | powerdist | sinh | sqrt | squared
    args: [] # see matplotlib docs
    kwargs: {} # see matplotlib docs
  title: true  # Display the title at the top of the animation
  movie_format: gif # The format of the movie. Imagemagik if gif else ffmpeg
pixcal: !pixcal_cfg
  method: threshold  # method to use laplacian|median|threshold
  step: 30 # Time interval for methods that need one
  use_weight: true # Use photon weights
  remake: false # Remake the calibration even if it exists
  n_sigma: 5.0 # number of standard deviations above/below the expected value for which a pixel will be flagged as hot/cold
  plots: none # none|last|all
speccal: !speccal_cfg
  photometry_type: aperture  # aperture | psf
  plots: summary # summary | none
  interpolation: linear #  linear | cubic | nearest
  wvl_bin_edges: [] # list of wavelength bin edges to use for determining the solution (in Angstroms). Defaults to nyquist sampling the energy resolution
  fit_order: 1 # order of the univariate spline to fit the soectrophotometric repsonse curve -must be shorter than the length of the wvl_bin_edges if specified
wavecal: !wavecal_cfg
  plots: summary  # summary or all
  histogram_models: # model types from wavecal_models.py to attempt to fit to the phase peak histograms
  - GaussianAndExponential
  bin_width: 2 # minimum bin width for the phase histogram. Larger widths will be used for low photon  count pixels (number)
  histogram_fit_attempts: 3 # how many times should the code try to fit each histogram model before giving up
  calibration_models: # model types from wavecal_models.py to attempt to fit to the phase-energy relationship
  - Quadratic
  - Linear
  dt: 500 # ignore photons which arrive this many microseconds from another photon (number)
  ncpu: 1 # Number of cores to use for fetching
  parallel_prefetch: false # use shared memory to load ALL the photon data into ram
wcscal: !wcscal_cfg
  plot: none  # none|all|summary
  interpolate: true # whether to inerpolate the image before PSF fitting. Recommended if an MKIDObservation is used or data is noisy
  sigma_psf: 2.0 # standard deviation of the point spread functions to fit in the image 
  param_guesses: # (optional) intitial guesses for hte wcs solution [platescale in x, platescale in y, pixels per conex move in x, pixels per conex move in y, device angle]
  - 1e-06
  - 1e-06
  - 50
  - 50
  - 45

```

**Comment by nswimmer** [comment]
Github will not let me upload files with the .YAML (or .YML) extension. For full files, I can send them anywhere.
